export type Grade = "A+" | "A" | "B+" | "B";

export type Chassis = "clamshell" | "convertible" | "creator" | "gaming";

export interface Laptop {
  id: string;
  slug: string;
  brand: string;
  model: string;
  tagline: string;
  category: "Ultrabook" | "Workstation" | "2-in-1" | "Creator" | "Gaming";
  chassis: Chassis;
  colorway: [string, string]; // gradient pair used by LaptopVisual
  grade: Grade;
  conditionScore: number; // 0-100, AI inspection score
  price: number;
  originalPrice: number;
  cpu: string;
  ram: string;
  storage: string;
  gpu: string;
  display: string;
  battery: string;
  weight: string;
  ports: string[];
  releaseYear: number;
  warrantyMonths: number;
  aiTag?: string;
  highlights: string[];
  included: string[];
  rating: number;
  reviewCount: number;
  inspectionChecks: { label: string; pass: boolean }[];
  benchmarks: { label: string; value: number; max: number; unit: string }[];
  photos?: string[]; // uploaded photo URLs; falls back to the generated LaptopVisual when absent
}

const inspection = (extra: string[] = []) => [
  { label: "Screen & pixel integrity", pass: true },
  { label: "Battery health ≥ 85%", pass: true },
  { label: "Keyboard & trackpad", pass: true },
  { label: "Hinge & chassis stress test", pass: true },
  { label: "Ports & I/O", pass: true },
  { label: "Thermal performance", pass: true },
  ...extra.map((label) => ({ label, pass: true })),
];

export const laptops: Laptop[] = [
  {
    id: "l1",
    slug: "macbook-pro-14-m2-pro",
    brand: "Apple",
    model: "MacBook Pro 14\u2033 M2 Pro",
    tagline: "Studio-grade power, restored to first-day form.",
    category: "Creator",
    chassis: "creator",
    colorway: ["#8a8d93", "#3a3c42"],
    grade: "A+",
    conditionScore: 98,
    price: 1449,
    originalPrice: 1999,
    cpu: "Apple M2 Pro \u2014 10-core CPU",
    ram: "16GB Unified Memory",
    storage: "512GB SSD",
    gpu: "16-core GPU",
    display: "14.2\u2033 Liquid Retina XDR, 120Hz",
    battery: "Up to 18 hrs",
    weight: "3.5 lb",
    ports: ["3x Thunderbolt 4", "HDMI 2.1", "SDXC", "MagSafe 3"],
    releaseYear: 2023,
    warrantyMonths: 12,
    aiTag: "Best for Creators",
    highlights: ["XDR mini-LED display", "Silent under sustained load", "ProRes hardware acceleration"],
    included: ["140W MagSafe charger", "Braided USB-C cable", "Restoration report"],
    rating: 4.9,
    reviewCount: 312,
    inspectionChecks: inspection(["Speaker distortion test", "Camera & mic array"]),
    benchmarks: [
      { label: "Multi-core", value: 92, max: 100, unit: "pts" },
      { label: "Graphics", value: 88, max: 100, unit: "pts" },
      { label: "Battery efficiency", value: 95, max: 100, unit: "pts" },
    ],
  },
  {
    id: "l2",
    slug: "macbook-air-13-m1",
    brand: "Apple",
    model: "MacBook Air 13\u2033 M1",
    tagline: "The one that made fanless cool again.",
    category: "Ultrabook",
    chassis: "clamshell",
    colorway: ["#d9d3c7", "#a39d8f"],
    grade: "A",
    conditionScore: 94,
    price: 649,
    originalPrice: 999,
    cpu: "Apple M1 \u2014 8-core CPU",
    ram: "8GB Unified Memory",
    storage: "256GB SSD",
    gpu: "7-core GPU",
    display: "13.3\u2033 Retina, True Tone",
    battery: "Up to 15 hrs",
    weight: "2.8 lb",
    ports: ["2x Thunderbolt / USB 4", "3.5mm jack"],
    releaseYear: 2020,
    warrantyMonths: 12,
    aiTag: "Best Value",
    highlights: ["Fanless silent operation", "All-day battery in real use", "Still receiving macOS updates"],
    included: ["30W USB-C charger", "USB-C cable", "Restoration report"],
    rating: 4.8,
    reviewCount: 587,
    inspectionChecks: inspection(),
    benchmarks: [
      { label: "Multi-core", value: 74, max: 100, unit: "pts" },
      { label: "Graphics", value: 68, max: 100, unit: "pts" },
      { label: "Battery efficiency", value: 91, max: 100, unit: "pts" },
    ],
  },
  {
    id: "l3",
    slug: "thinkpad-x1-carbon-gen10",
    brand: "Lenovo",
    model: "ThinkPad X1 Carbon Gen 10",
    tagline: "Carbon-fiber tough, boardroom quiet.",
    category: "Ultrabook",
    chassis: "clamshell",
    colorway: ["#26282e", "#0e0f12"],
    grade: "A",
    conditionScore: 93,
    price: 799,
    originalPrice: 1899,
    cpu: "Intel Core i7-1270P",
    ram: "16GB LPDDR5",
    storage: "512GB SSD",
    gpu: "Intel Iris Xe",
    display: "14\u2033 WUXGA IPS, 400 nits",
    battery: "Up to 13 hrs",
    weight: "2.5 lb",
    ports: ["2x Thunderbolt 4", "2x USB-A", "HDMI 2.0", "microSD"],
    releaseYear: 2022,
    warrantyMonths: 12,
    aiTag: "Best for Business",
    highlights: ["MIL-STD-810H tested chassis", "TrackPoint + spill-resistant keyboard", "vPro remote manageability"],
    included: ["65W USB-C charger", "Restoration report"],
    rating: 4.7,
    reviewCount: 204,
    inspectionChecks: inspection(["TPM 2.0 verification"]),
    benchmarks: [
      { label: "Multi-core", value: 79, max: 100, unit: "pts" },
      { label: "Graphics", value: 52, max: 100, unit: "pts" },
      { label: "Battery efficiency", value: 82, max: 100, unit: "pts" },
    ],
  },
  {
    id: "l4",
    slug: "dell-xps-13-plus",
    brand: "Dell",
    model: "XPS 13 Plus",
    tagline: "Edge-to-edge glass, zero-lattice keyboard.",
    category: "Ultrabook",
    chassis: "clamshell",
    colorway: ["#c9cbd1", "#8b8e97"],
    grade: "A",
    conditionScore: 92,
    price: 899,
    originalPrice: 1799,
    cpu: "Intel Core i7-1280P",
    ram: "16GB LPDDR5",
    storage: "512GB SSD",
    gpu: "Intel Iris Xe",
    display: "13.4\u2033 OLED 3.5K Touch",
    battery: "Up to 12 hrs",
    weight: "2.7 lb",
    ports: ["2x Thunderbolt 4"],
    releaseYear: 2022,
    warrantyMonths: 12,
    highlights: ["Capacitive haptic touch row", "OLED contrast for design work", "Near-borderless display"],
    included: ["60W USB-C charger", "USB-C to USB-A dongle", "Restoration report"],
    rating: 4.6,
    reviewCount: 168,
    inspectionChecks: inspection(),
    benchmarks: [
      { label: "Multi-core", value: 81, max: 100, unit: "pts" },
      { label: "Graphics", value: 54, max: 100, unit: "pts" },
      { label: "Battery efficiency", value: 74, max: 100, unit: "pts" },
    ],
  },
  {
    id: "l5",
    slug: "surface-laptop-5-15",
    brand: "Microsoft",
    model: "Surface Laptop 5 15\u2033",
    tagline: "Alcantara comfort, Windows done clean.",
    category: "Ultrabook",
    chassis: "clamshell",
    colorway: ["#3f5d7d", "#22364a"],
    grade: "B+",
    conditionScore: 89,
    price: 749,
    originalPrice: 1699,
    cpu: "Intel Core i7-1255U",
    ram: "16GB LPDDR5x",
    storage: "512GB SSD",
    gpu: "Intel Iris Xe",
    display: "15\u2033 PixelSense Touch",
    battery: "Up to 17 hrs",
    weight: "3.4 lb",
    ports: ["1x Thunderbolt 4", "1x USB-A", "Surface Connect"],
    releaseYear: 2022,
    warrantyMonths: 9,
    highlights: ["Alcantara palm rest", "Studio Mic array", "Windows Hello IR camera"],
    included: ["65W Surface charger", "Restoration report"],
    rating: 4.5,
    reviewCount: 121,
    inspectionChecks: inspection(),
    benchmarks: [
      { label: "Multi-core", value: 70, max: 100, unit: "pts" },
      { label: "Graphics", value: 50, max: 100, unit: "pts" },
      { label: "Battery efficiency", value: 86, max: 100, unit: "pts" },
    ],
  },
  {
    id: "l6",
    slug: "macbook-pro-16-m1-max",
    brand: "Apple",
    model: "MacBook Pro 16\u2033 M1 Max",
    tagline: "Render farms fit in backpacks now.",
    category: "Workstation",
    chassis: "creator",
    colorway: ["#3a3c42", "#17181c"],
    grade: "A",
    conditionScore: 95,
    price: 1899,
    originalPrice: 3499,
    cpu: "Apple M1 Max \u2014 10-core CPU",
    ram: "32GB Unified Memory",
    storage: "1TB SSD",
    gpu: "32-core GPU",
    display: "16.2\u2033 Liquid Retina XDR, 120Hz",
    battery: "Up to 21 hrs",
    weight: "4.7 lb",
    ports: ["3x Thunderbolt 4", "HDMI 2.1", "SDXC", "MagSafe 3"],
    releaseYear: 2021,
    warrantyMonths: 12,
    aiTag: "Best for Video Editing",
    highlights: ["Handles 8K ProRes timelines", "32GB unified memory ceiling", "Studio-referenced display"],
    included: ["140W MagSafe charger", "Restoration report"],
    rating: 4.9,
    reviewCount: 96,
    inspectionChecks: inspection(["Speaker distortion test"]),
    benchmarks: [
      { label: "Multi-core", value: 96, max: 100, unit: "pts" },
      { label: "Graphics", value: 97, max: 100, unit: "pts" },
      { label: "Battery efficiency", value: 90, max: 100, unit: "pts" },
    ],
  },
  {
    id: "l7",
    slug: "thinkpad-t14-gen3",
    brand: "Lenovo",
    model: "ThinkPad T14 Gen 3",
    tagline: "The fleet workhorse, IT-department approved.",
    category: "Ultrabook",
    chassis: "clamshell",
    colorway: ["#1e2024", "#101114"],
    grade: "B+",
    conditionScore: 88,
    price: 549,
    originalPrice: 1299,
    cpu: "Intel Core i5-1245U",
    ram: "16GB DDR4",
    storage: "256GB SSD",
    gpu: "Intel Iris Xe",
    display: "14\u2033 FHD IPS",
    battery: "Up to 11 hrs",
    weight: "3.1 lb",
    ports: ["2x Thunderbolt 4", "2x USB-A", "HDMI", "Ethernet"],
    releaseYear: 2022,
    warrantyMonths: 9,
    aiTag: "Best for Fleets",
    highlights: ["Ethernet port included", "Field-replaceable battery", "Bulk-order friendly"],
    included: ["65W charger", "Restoration report"],
    rating: 4.5,
    reviewCount: 143,
    inspectionChecks: inspection(["TPM 2.0 verification"]),
    benchmarks: [
      { label: "Multi-core", value: 65, max: 100, unit: "pts" },
      { label: "Graphics", value: 46, max: 100, unit: "pts" },
      { label: "Battery efficiency", value: 78, max: 100, unit: "pts" },
    ],
  },
  {
    id: "l8",
    slug: "razer-blade-15-2022",
    brand: "Razer",
    model: "Blade 15 (2022)",
    tagline: "CNC aluminum with a GPU that bites.",
    category: "Gaming",
    chassis: "gaming",
    colorway: ["#1a1c20", "#0a0b0d"],
    grade: "A",
    conditionScore: 91,
    price: 1599,
    originalPrice: 2899,
    cpu: "Intel Core i7-12800H",
    ram: "16GB DDR5",
    storage: "1TB SSD",
    gpu: "NVIDIA RTX 3070 Ti",
    display: "15.6\u2033 QHD 240Hz",
    battery: "Up to 6 hrs",
    weight: "4.4 lb",
    ports: ["1x Thunderbolt 4", "3x USB-A", "HDMI 2.1", "UHS-III SD"],
    releaseYear: 2022,
    warrantyMonths: 12,
    aiTag: "Best for Gaming",
    highlights: ["240Hz QHD panel", "Per-key RGB", "Vapor chamber cooling"],
    included: ["230W charger", "Restoration report"],
    rating: 4.7,
    reviewCount: 88,
    inspectionChecks: inspection(["GPU thermal throttle test", "Fan bearing noise check"]),
    benchmarks: [
      { label: "Multi-core", value: 85, max: 100, unit: "pts" },
      { label: "Graphics", value: 89, max: 100, unit: "pts" },
      { label: "Battery efficiency", value: 42, max: 100, unit: "pts" },
    ],
  },
  {
    id: "l9",
    slug: "zenbook-14-oled",
    brand: "ASUS",
    model: "Zenbook 14 OLED",
    tagline: "Pocket-sized OLED for color obsessives.",
    category: "Ultrabook",
    chassis: "clamshell",
    colorway: ["#33465a", "#1c2733"],
    grade: "A",
    conditionScore: 92,
    price: 629,
    originalPrice: 1099,
    cpu: "AMD Ryzen 7 5800H",
    ram: "16GB LPDDR4x",
    storage: "512GB SSD",
    gpu: "AMD Radeon Graphics",
    display: "14\u2033 2.8K OLED, 90Hz",
    battery: "Up to 10 hrs",
    weight: "2.9 lb",
    ports: ["1x Thunderbolt 4", "1x USB-A 3.2", "HDMI", "microSD"],
    releaseYear: 2021,
    warrantyMonths: 9,
    highlights: ["100% DCI-P3 OLED", "Pantone validated color", "Harman Kardon speakers"],
    included: ["65W charger", "Sleeve", "Restoration report"],
    rating: 4.6,
    reviewCount: 77,
    inspectionChecks: inspection(),
    benchmarks: [
      { label: "Multi-core", value: 77, max: 100, unit: "pts" },
      { label: "Graphics", value: 58, max: 100, unit: "pts" },
      { label: "Battery efficiency", value: 71, max: 100, unit: "pts" },
    ],
  },
  {
    id: "l10",
    slug: "elitebook-840-g9",
    brand: "HP",
    model: "EliteBook 840 G9",
    tagline: "Enterprise security, quietly excellent.",
    category: "Ultrabook",
    chassis: "clamshell",
    colorway: ["#3b3d42", "#202226"],
    grade: "A",
    conditionScore: 93,
    price: 719,
    originalPrice: 1599,
    cpu: "Intel Core i5-1240P",
    ram: "16GB DDR5",
    storage: "256GB SSD",
    gpu: "Intel Iris Xe",
    display: "14\u2033 WUXGA IPS, Privacy Screen",
    battery: "Up to 13 hrs",
    weight: "2.9 lb",
    ports: ["2x Thunderbolt 4", "2x USB-A", "HDMI"],
    releaseYear: 2022,
    warrantyMonths: 12,
    aiTag: "Best for Business",
    highlights: ["Built-in privacy screen", "HP Sure Click isolation", "Self-healing BIOS"],
    included: ["65W charger", "Restoration report"],
    rating: 4.6,
    reviewCount: 59,
    inspectionChecks: inspection(["TPM 2.0 verification"]),
    benchmarks: [
      { label: "Multi-core", value: 75, max: 100, unit: "pts" },
      { label: "Graphics", value: 51, max: 100, unit: "pts" },
      { label: "Battery efficiency", value: 80, max: 100, unit: "pts" },
    ],
  },
  {
    id: "l11",
    slug: "macbook-air-15-m2",
    brand: "Apple",
    model: "MacBook Air 15\u2033 M2",
    tagline: "The big-screen Air, still whisper quiet.",
    category: "Ultrabook",
    chassis: "clamshell",
    colorway: ["#7d8890", "#48525a"],
    grade: "A+",
    conditionScore: 97,
    price: 1099,
    originalPrice: 1499,
    cpu: "Apple M2 \u2014 8-core CPU",
    ram: "16GB Unified Memory",
    storage: "512GB SSD",
    gpu: "10-core GPU",
    display: "15.3\u2033 Liquid Retina",
    battery: "Up to 18 hrs",
    weight: "3.3 lb",
    ports: ["2x Thunderbolt / USB 4", "MagSafe 3"],
    releaseYear: 2023,
    warrantyMonths: 12,
    aiTag: "Best Value",
    highlights: ["Six-speaker sound system", "Fanless yet sustained", "Large canvas for spreadsheets"],
    included: ["35W dual charger", "Restoration report"],
    rating: 4.9,
    reviewCount: 214,
    inspectionChecks: inspection(),
    benchmarks: [
      { label: "Multi-core", value: 83, max: 100, unit: "pts" },
      { label: "Graphics", value: 76, max: 100, unit: "pts" },
      { label: "Battery efficiency", value: 93, max: 100, unit: "pts" },
    ],
  },
  {
    id: "l12",
    slug: "latitude-9420-2in1",
    brand: "Dell",
    model: "Latitude 9420 2-in-1",
    tagline: "Folds flat, works everywhere.",
    category: "2-in-1",
    chassis: "convertible",
    colorway: ["#4a4d54", "#26282d"],
    grade: "B+",
    conditionScore: 87,
    price: 679,
    originalPrice: 1799,
    cpu: "Intel Core i7-1185G7",
    ram: "16GB LPDDR4x",
    storage: "512GB SSD",
    gpu: "Intel Iris Xe",
    display: "14\u2033 FHD Touch, 360\u00b0 hinge",
    battery: "Up to 12 hrs",
    weight: "3.2 lb",
    ports: ["2x Thunderbolt 4", "1x USB-A"],
    releaseYear: 2021,
    warrantyMonths: 9,
    highlights: ["360\u00b0 tablet mode", "Active pen supported", "Sculpted low-profile keys"],
    included: ["65W charger", "Restoration report"],
    rating: 4.4,
    reviewCount: 41,
    inspectionChecks: inspection(["Hinge rotation test x500"]),
    benchmarks: [
      { label: "Multi-core", value: 68, max: 100, unit: "pts" },
      { label: "Graphics", value: 49, max: 100, unit: "pts" },
      { label: "Battery efficiency", value: 76, max: 100, unit: "pts" },
    ],
  },
  {
    id: "l13",
    slug: "spectre-x360-13",
    brand: "HP",
    model: "Spectre x360 13",
    tagline: "Gem-cut edges, convertible everything.",
    category: "2-in-1",
    chassis: "convertible",
    colorway: ["#3c4a52", "#1d262b"],
    grade: "A",
    conditionScore: 90,
    price: 719,
    originalPrice: 1449,
    cpu: "Intel Core i7-1255U",
    ram: "16GB LPDDR4x",
    storage: "512GB SSD",
    gpu: "Intel Iris Xe",
    display: "13.5\u2033 3K2K OLED Touch",
    battery: "Up to 14 hrs",
    weight: "3.0 lb",
    ports: ["2x Thunderbolt 4", "1x USB-A"],
    releaseYear: 2022,
    warrantyMonths: 9,
    highlights: ["Gem-cut chassis design", "Included Tilt Pen", "3:2 aspect for reading"],
    included: ["65W charger", "Active pen", "Restoration report"],
    rating: 4.6,
    reviewCount: 63,
    inspectionChecks: inspection(["Hinge rotation test x500"]),
    benchmarks: [
      { label: "Multi-core", value: 74, max: 100, unit: "pts" },
      { label: "Graphics", value: 53, max: 100, unit: "pts" },
      { label: "Battery efficiency", value: 79, max: 100, unit: "pts" },
    ],
  },
  {
    id: "l14",
    slug: "thinkpad-x1-yoga-gen7",
    brand: "Lenovo",
    model: "ThinkPad X1 Yoga Gen 7",
    tagline: "Business convertible with a garaged pen.",
    category: "2-in-1",
    chassis: "convertible",
    colorway: ["#26282e", "#121317"],
    grade: "A",
    conditionScore: 91,
    price: 849,
    originalPrice: 2099,
    cpu: "Intel Core i7-1270P",
    ram: "16GB LPDDR5",
    storage: "512GB SSD",
    gpu: "Intel Iris Xe",
    display: "14\u2033 WUXGA Touch",
    battery: "Up to 12 hrs",
    weight: "3.0 lb",
    ports: ["2x Thunderbolt 4", "1x USB-A", "HDMI"],
    releaseYear: 2022,
    warrantyMonths: 12,
    highlights: ["Garaged & charging pen", "MIL-STD-810H tested", "Dolby Atmos speakers"],
    included: ["65W charger", "ThinkPad Pen Pro", "Restoration report"],
    rating: 4.7,
    reviewCount: 52,
    inspectionChecks: inspection(["Hinge rotation test x500", "TPM 2.0 verification"]),
    benchmarks: [
      { label: "Multi-core", value: 78, max: 100, unit: "pts" },
      { label: "Graphics", value: 52, max: 100, unit: "pts" },
      { label: "Battery efficiency", value: 80, max: 100, unit: "pts" },
    ],
  },
  {
    id: "l15",
    slug: "macbook-pro-13-m2",
    brand: "Apple",
    model: "MacBook Pro 13\u2033 M2",
    tagline: "The last of the Touch Bar era, still fast.",
    category: "Ultrabook",
    chassis: "clamshell",
    colorway: ["#8a8d93", "#4c4e54"],
    grade: "A",
    conditionScore: 94,
    price: 899,
    originalPrice: 1299,
    cpu: "Apple M2 \u2014 8-core CPU",
    ram: "8GB Unified Memory",
    storage: "256GB SSD",
    gpu: "10-core GPU",
    display: "13.3\u2033 Retina, True Tone",
    battery: "Up to 20 hrs",
    weight: "3.0 lb",
    ports: ["2x Thunderbolt / USB 4", "3.5mm jack"],
    releaseYear: 2022,
    warrantyMonths: 12,
    highlights: ["Longest battery life in the lineup", "Active cooling for sustained loads", "Familiar, proven chassis"],
    included: ["67W charger", "Restoration report"],
    rating: 4.6,
    reviewCount: 132,
    inspectionChecks: inspection(),
    benchmarks: [
      { label: "Multi-core", value: 80, max: 100, unit: "pts" },
      { label: "Graphics", value: 74, max: 100, unit: "pts" },
      { label: "Battery efficiency", value: 96, max: 100, unit: "pts" },
    ],
  },
  {
    id: "l16",
    slug: "yoga-9i-14",
    brand: "Lenovo",
    model: "Yoga 9i 14",
    tagline: "Rotating soundbar hinge, jewelry-grade finish.",
    category: "2-in-1",
    chassis: "convertible",
    colorway: ["#5a4c3a", "#332a1f"],
    grade: "B+",
    conditionScore: 88,
    price: 599,
    originalPrice: 1399,
    cpu: "Intel Core i7-1260P",
    ram: "16GB LPDDR5",
    storage: "512GB SSD",
    gpu: "Intel Iris Xe",
    display: "14\u2033 2.8K OLED Touch",
    battery: "Up to 11 hrs",
    weight: "3.0 lb",
    ports: ["2x Thunderbolt 4", "1x USB-A"],
    releaseYear: 2022,
    warrantyMonths: 9,
    highlights: ["Rotating soundbar hinge", "Bowers & Wilkins tuning", "Machined aluminum shell"],
    included: ["65W charger", "Active pen", "Restoration report"],
    rating: 4.5,
    reviewCount: 38,
    inspectionChecks: inspection(["Hinge rotation test x500"]),
    benchmarks: [
      { label: "Multi-core", value: 76, max: 100, unit: "pts" },
      { label: "Graphics", value: 52, max: 100, unit: "pts" },
      { label: "Battery efficiency", value: 73, max: 100, unit: "pts" },
    ],
  },
  {
    id: "l17",
    slug: "xps-15-9520",
    brand: "Dell",
    model: "XPS 15 9520",
    tagline: "Creator canvas with a discrete GPU.",
    category: "Creator",
    chassis: "creator",
    colorway: ["#c9cbd1", "#6a6d75"],
    grade: "A",
    conditionScore: 92,
    price: 1349,
    originalPrice: 2499,
    cpu: "Intel Core i7-12700H",
    ram: "32GB DDR5",
    storage: "1TB SSD",
    gpu: "NVIDIA RTX 3050 Ti",
    display: "15.6\u2033 3.5K OLED Touch",
    battery: "Up to 10 hrs",
    weight: "4.2 lb",
    ports: ["2x Thunderbolt 4", "1x USB-A", "SD card"],
    releaseYear: 2022,
    warrantyMonths: 12,
    aiTag: "Best for Creators",
    highlights: ["3.5K OLED for grading", "CNC machined aluminum", "Quad speaker array"],
    included: ["130W charger", "Restoration report"],
    rating: 4.7,
    reviewCount: 71,
    inspectionChecks: inspection(["GPU thermal throttle test"]),
    benchmarks: [
      { label: "Multi-core", value: 86, max: 100, unit: "pts" },
      { label: "Graphics", value: 71, max: 100, unit: "pts" },
      { label: "Battery efficiency", value: 65, max: 100, unit: "pts" },
    ],
  },
  {
    id: "l18",
    slug: "rog-zephyrus-g14",
    brand: "ASUS",
    model: "ROG Zephyrus G14",
    tagline: "AniMe Matrix lid, desktop-class frame rates.",
    category: "Gaming",
    chassis: "gaming",
    colorway: ["#e7e9ec", "#9a9ca2"],
    grade: "A",
    conditionScore: 90,
    price: 1249,
    originalPrice: 2199,
    cpu: "AMD Ryzen 9 6900HS",
    ram: "16GB DDR5",
    storage: "1TB SSD",
    gpu: "NVIDIA RTX 3060",
    display: "14\u2033 QHD 120Hz",
    battery: "Up to 8 hrs",
    weight: "3.6 lb",
    ports: ["1x USB-C 4", "2x USB-A", "HDMI 2.0b"],
    releaseYear: 2022,
    warrantyMonths: 9,
    aiTag: "Best for Gaming",
    highlights: ["AniMe Matrix LED lid", "Sub-4lb gaming chassis", "Dolby Atmos speakers"],
    included: ["180W charger", "Restoration report"],
    rating: 4.6,
    reviewCount: 47,
    inspectionChecks: inspection(["GPU thermal throttle test", "Fan bearing noise check"]),
    benchmarks: [
      { label: "Multi-core", value: 88, max: 100, unit: "pts" },
      { label: "Graphics", value: 79, max: 100, unit: "pts" },
      { label: "Battery efficiency", value: 48, max: 100, unit: "pts" },
    ],
  },
  {
    id: "l19",
    slug: "elitebook-x360-1040-g9",
    brand: "HP",
    model: "EliteBook x360 1040 G9",
    tagline: "The 2-in-1 IT actually approves.",
    category: "2-in-1",
    chassis: "convertible",
    colorway: ["#3b3d42", "#1a1b1e"],
    grade: "A",
    conditionScore: 91,
    price: 799,
    originalPrice: 1899,
    cpu: "Intel Core i7-1265U",
    ram: "16GB LPDDR5",
    storage: "512GB SSD",
    gpu: "Intel Iris Xe",
    display: "14\u2033 WUXGA Touch, Privacy Screen",
    battery: "Up to 13 hrs",
    weight: "2.9 lb",
    ports: ["2x Thunderbolt 4", "1x USB-A", "HDMI"],
    releaseYear: 2022,
    warrantyMonths: 12,
    highlights: ["Sure View privacy screen", "Tile tracking built in", "5G-ready variant available"],
    included: ["65W charger", "Restoration report"],
    rating: 4.6,
    reviewCount: 33,
    inspectionChecks: inspection(["Hinge rotation test x500", "TPM 2.0 verification"]),
    benchmarks: [
      { label: "Multi-core", value: 77, max: 100, unit: "pts" },
      { label: "Graphics", value: 53, max: 100, unit: "pts" },
      { label: "Battery efficiency", value: 81, max: 100, unit: "pts" },
    ],
  },
  {
    id: "l20",
    slug: "macbook-pro-16-m3-pro",
    brand: "Apple",
    model: "MacBook Pro 16\u2033 M3 Pro",
    tagline: "The current flagship, at a former price.",
    category: "Workstation",
    chassis: "creator",
    colorway: ["#17181c", "#050506"],
    grade: "A+",
    conditionScore: 99,
    price: 2299,
    originalPrice: 3199,
    cpu: "Apple M3 Pro \u2014 12-core CPU",
    ram: "18GB Unified Memory",
    storage: "512GB SSD",
    gpu: "18-core GPU",
    display: "16.2\u2033 Liquid Retina XDR, 120Hz",
    battery: "Up to 22 hrs",
    weight: "4.8 lb",
    ports: ["3x Thunderbolt 4", "HDMI 2.1", "SDXC", "MagSafe 3"],
    releaseYear: 2023,
    warrantyMonths: 12,
    aiTag: "Best for Video Editing",
    highlights: ["Latest-gen efficiency cores", "1600-nit peak HDR", "Space Black finish"],
    included: ["140W MagSafe charger", "Restoration report"],
    rating: 4.9,
    reviewCount: 28,
    inspectionChecks: inspection(["Speaker distortion test"]),
    benchmarks: [
      { label: "Multi-core", value: 98, max: 100, unit: "pts" },
      { label: "Graphics", value: 93, max: 100, unit: "pts" },
      { label: "Battery efficiency", value: 97, max: 100, unit: "pts" },
    ],
  },
  {
    id: "l21",
    slug: "thinkpad-e14-gen4",
    brand: "Lenovo",
    model: "ThinkPad E14 Gen 4",
    tagline: "Entry ThinkPad, senior-level reliability.",
    category: "Ultrabook",
    chassis: "clamshell",
    colorway: ["#2a2c33", "#151619"],
    grade: "B",
    conditionScore: 85,
    price: 429,
    originalPrice: 899,
    cpu: "AMD Ryzen 5 5625U",
    ram: "8GB DDR4",
    storage: "256GB SSD",
    gpu: "AMD Radeon Graphics",
    display: "14\u2033 FHD IPS",
    battery: "Up to 10 hrs",
    weight: "3.3 lb",
    ports: ["1x USB-C", "2x USB-A", "HDMI"],
    releaseYear: 2022,
    warrantyMonths: 6,
    aiTag: "Best for Students",
    highlights: ["Lightest ThinkPad entry point", "Spill-resistant keyboard", "Great for note-taking loads"],
    included: ["45W charger", "Restoration report"],
    rating: 4.3,
    reviewCount: 96,
    inspectionChecks: inspection(),
    benchmarks: [
      { label: "Multi-core", value: 58, max: 100, unit: "pts" },
      { label: "Graphics", value: 41, max: 100, unit: "pts" },
      { label: "Battery efficiency", value: 75, max: 100, unit: "pts" },
    ],
  },
  {
    id: "l22",
    slug: "surface-laptop-studio",
    brand: "Microsoft",
    model: "Surface Laptop Studio",
    tagline: "A hinge that turns into a drafting table.",
    category: "Creator",
    chassis: "creator",
    colorway: ["#4a4d54", "#232529"],
    grade: "A",
    conditionScore: 90,
    price: 1399,
    originalPrice: 2699,
    cpu: "Intel Core i7-11370H",
    ram: "32GB LPDDR4x",
    storage: "1TB SSD",
    gpu: "NVIDIA RTX 3050 Ti",
    display: "14.4\u2033 PixelSense Flow, 120Hz",
    battery: "Up to 9 hrs",
    weight: "4.0 lb",
    ports: ["2x Thunderbolt 4", "Surface Connect"],
    releaseYear: 2022,
    warrantyMonths: 9,
    highlights: ["Dynamic Woven Hinge", "Slim Pen 2 haptics", "Studio mode for sketching"],
    included: ["Surface Connect charger", "Restoration report"],
    rating: 4.6,
    reviewCount: 29,
    inspectionChecks: inspection(["Hinge rotation test x500", "GPU thermal throttle test"]),
    benchmarks: [
      { label: "Multi-core", value: 69, max: 100, unit: "pts" },
      { label: "Graphics", value: 66, max: 100, unit: "pts" },
      { label: "Battery efficiency", value: 60, max: 100, unit: "pts" },
    ],
  },
  {
    id: "l23",
    slug: "macbook-air-13-m2",
    brand: "Apple",
    model: "MacBook Air 13\u2033 M2",
    tagline: "Redesigned, flat-edged, still no fan.",
    category: "Ultrabook",
    chassis: "clamshell",
    colorway: ["#d9d3c7", "#8b8578"],
    grade: "A+",
    conditionScore: 97,
    price: 899,
    originalPrice: 1199,
    cpu: "Apple M2 \u2014 8-core CPU",
    ram: "8GB Unified Memory",
    storage: "256GB SSD",
    gpu: "8-core GPU",
    display: "13.6\u2033 Liquid Retina",
    battery: "Up to 18 hrs",
    weight: "2.7 lb",
    ports: ["2x Thunderbolt / USB 4", "MagSafe 3"],
    releaseYear: 2022,
    warrantyMonths: 12,
    aiTag: "Best Value",
    highlights: ["Redesigned flat-edge chassis", "MagSafe returns", "1080p FaceTime camera"],
    included: ["30W charger", "Restoration report"],
    rating: 4.8,
    reviewCount: 251,
    inspectionChecks: inspection(),
    benchmarks: [
      { label: "Multi-core", value: 81, max: 100, unit: "pts" },
      { label: "Graphics", value: 70, max: 100, unit: "pts" },
      { label: "Battery efficiency", value: 92, max: 100, unit: "pts" },
    ],
  },
  {
    id: "l24",
    slug: "latitude-5430",
    brand: "Dell",
    model: "Latitude 5430",
    tagline: "Fleet-ready, field-serviceable, forgettable price.",
    category: "Ultrabook",
    chassis: "clamshell",
    colorway: ["#4a4d54", "#26282d"],
    grade: "B",
    conditionScore: 84,
    price: 389,
    originalPrice: 1099,
    cpu: "Intel Core i5-1235U",
    ram: "8GB DDR4",
    storage: "256GB SSD",
    gpu: "Intel Iris Xe",
    display: "14\u2033 FHD IPS",
    battery: "Up to 10 hrs",
    weight: "3.4 lb",
    ports: ["1x Thunderbolt 4", "2x USB-A", "HDMI", "Ethernet"],
    releaseYear: 2022,
    warrantyMonths: 6,
    aiTag: "Best for Fleets",
    highlights: ["Ethernet + full-size ports", "Field-replaceable RAM & SSD", "Volume-friendly pricing"],
    included: ["65W charger", "Restoration report"],
    rating: 4.3,
    reviewCount: 112,
    inspectionChecks: inspection(["TPM 2.0 verification"]),
    benchmarks: [
      { label: "Multi-core", value: 62, max: 100, unit: "pts" },
      { label: "Graphics", value: 44, max: 100, unit: "pts" },
      { label: "Battery efficiency", value: 74, max: 100, unit: "pts" },
    ],
  },
  {
    id: "l25",
    slug: "zenbook-pro-14-duo",
    brand: "ASUS",
    model: "Zenbook Pro 14 Duo",
    tagline: "Two screens, one very patient hinge.",
    category: "Creator",
    chassis: "creator",
    colorway: ["#26282e", "#101114"],
    grade: "B+",
    conditionScore: 87,
    price: 1099,
    originalPrice: 2299,
    cpu: "Intel Core i9-12900H",
    ram: "32GB DDR5",
    storage: "1TB SSD",
    gpu: "NVIDIA RTX 3050 Ti",
    display: "14.5\u2033 2.8K OLED + ScreenPad Plus",
    battery: "Up to 7 hrs",
    weight: "4.4 lb",
    ports: ["1x Thunderbolt 4", "1x USB-A", "HDMI"],
    releaseYear: 2022,
    warrantyMonths: 9,
    highlights: ["Secondary ScreenPad display", "Bundled stylus & palm rest", "OLED main panel"],
    included: ["180W charger", "Palm rest", "Stylus", "Restoration report"],
    rating: 4.5,
    reviewCount: 22,
    inspectionChecks: inspection(["GPU thermal throttle test", "Secondary display uniformity"]),
    benchmarks: [
      { label: "Multi-core", value: 91, max: 100, unit: "pts" },
      { label: "Graphics", value: 68, max: 100, unit: "pts" },
      { label: "Battery efficiency", value: 45, max: 100, unit: "pts" },
    ],
  },
  {
    id: "l26",
    slug: "thinkpad-p1-gen5",
    brand: "Lenovo",
    model: "ThinkPad P1 Gen 5",
    tagline: "Mobile workstation for CAD that never sleeps.",
    category: "Workstation",
    chassis: "creator",
    colorway: ["#1e2024", "#0c0d0f"],
    grade: "A",
    conditionScore: 92,
    price: 1699,
    originalPrice: 3299,
    cpu: "Intel Core i7-12800H",
    ram: "32GB DDR5",
    storage: "1TB SSD",
    gpu: "NVIDIA RTX A2000",
    display: "16\u2033 QHD+ IPS, 165Hz",
    battery: "Up to 9 hrs",
    weight: "4.5 lb",
    ports: ["2x Thunderbolt 4", "2x USB-A", "HDMI", "SD Express"],
    releaseYear: 2022,
    warrantyMonths: 12,
    aiTag: "Best for Engineering",
    highlights: ["ISV-certified RTX A2000", "165Hz for CAD panning", "MIL-STD-810H tested"],
    included: ["230W charger", "Restoration report"],
    rating: 4.8,
    reviewCount: 19,
    inspectionChecks: inspection(["GPU thermal throttle test", "TPM 2.0 verification"]),
    benchmarks: [
      { label: "Multi-core", value: 90, max: 100, unit: "pts" },
      { label: "Graphics", value: 82, max: 100, unit: "pts" },
      { label: "Battery efficiency", value: 55, max: 100, unit: "pts" },
    ],
  },
  {
    id: "l27",
    slug: "elite-dragonfly-g3",
    brand: "HP",
    model: "Elite Dragonfly G3",
    tagline: "Under 2.2 pounds of magnesium alloy.",
    category: "Ultrabook",
    chassis: "convertible",
    colorway: ["#3f5d7d", "#1c2c3c"],
    grade: "A",
    conditionScore: 93,
    price: 949,
    originalPrice: 2199,
    cpu: "Intel Core i7-1265U",
    ram: "16GB LPDDR5",
    storage: "512GB SSD",
    gpu: "Intel Iris Xe",
    display: "13.5\u2033 3K2K Touch",
    battery: "Up to 15 hrs",
    weight: "2.2 lb",
    ports: ["2x Thunderbolt 4", "1x USB-A"],
    releaseYear: 2022,
    warrantyMonths: 12,
    highlights: ["Lightest business convertible", "Magnesium alloy chassis", "Bang & Olufsen audio"],
    included: ["65W charger", "Restoration report"],
    rating: 4.7,
    reviewCount: 24,
    inspectionChecks: inspection(["Hinge rotation test x500"]),
    benchmarks: [
      { label: "Multi-core", value: 76, max: 100, unit: "pts" },
      { label: "Graphics", value: 53, max: 100, unit: "pts" },
      { label: "Battery efficiency", value: 83, max: 100, unit: "pts" },
    ],
  },
  {
    id: "l28",
    slug: "macbook-pro-14-m3",
    brand: "Apple",
    model: "MacBook Pro 14\u2033 M3",
    tagline: "The entry XDR MacBook, freshly restored.",
    category: "Creator",
    chassis: "creator",
    colorway: ["#17181c", "#050506"],
    grade: "A+",
    conditionScore: 98,
    price: 1599,
    originalPrice: 1999,
    cpu: "Apple M3 \u2014 8-core CPU",
    ram: "8GB Unified Memory",
    storage: "512GB SSD",
    gpu: "10-core GPU",
    display: "14.2\u2033 Liquid Retina XDR",
    battery: "Up to 22 hrs",
    weight: "3.5 lb",
    ports: ["3x Thunderbolt 4", "HDMI 2.1", "SDXC", "MagSafe 3"],
    releaseYear: 2023,
    warrantyMonths: 12,
    highlights: ["Space Black finish", "1600-nit peak HDR", "22-hour real-world battery"],
    included: ["70W charger", "Restoration report"],
    rating: 4.9,
    reviewCount: 44,
    inspectionChecks: inspection(),
    benchmarks: [
      { label: "Multi-core", value: 89, max: 100, unit: "pts" },
      { label: "Graphics", value: 84, max: 100, unit: "pts" },
      { label: "Battery efficiency", value: 96, max: 100, unit: "pts" },
    ],
  },
  {
    id: "l29",
    slug: "legion-slim-7-gen7",
    brand: "Lenovo",
    model: "Legion Slim 7 Gen 7",
    tagline: "Gaming power in a business-casual shell.",
    category: "Gaming",
    chassis: "gaming",
    colorway: ["#5a5f68", "#2a2d33"],
    grade: "A",
    conditionScore: 90,
    price: 1349,
    originalPrice: 2399,
    cpu: "AMD Ryzen 9 6900HX",
    ram: "16GB DDR5",
    storage: "1TB SSD",
    gpu: "NVIDIA RTX 3070 Ti",
    display: "16\u2033 QHD+ 165Hz",
    battery: "Up to 7 hrs",
    weight: "4.4 lb",
    ports: ["1x USB-C 3.2", "1x Thunderbolt 4", "2x USB-A", "HDMI 2.1"],
    releaseYear: 2022,
    warrantyMonths: 9,
    aiTag: "Best for Gaming",
    highlights: ["No gamer-branding on the lid", "165Hz QHD+ panel", "Legion Coldfront cooling"],
    included: ["230W charger", "Restoration report"],
    rating: 4.6,
    reviewCount: 31,
    inspectionChecks: inspection(["GPU thermal throttle test", "Fan bearing noise check"]),
    benchmarks: [
      { label: "Multi-core", value: 87, max: 100, unit: "pts" },
      { label: "Graphics", value: 85, max: 100, unit: "pts" },
      { label: "Battery efficiency", value: 44, max: 100, unit: "pts" },
    ],
  },
  {
    id: "l30",
    slug: "vivobook-s15-oled",
    brand: "ASUS",
    model: "Vivobook S15 OLED",
    tagline: "OLED glow without the flagship bill.",
    category: "Ultrabook",
    chassis: "clamshell",
    colorway: ["#3a4a5a", "#1c2833"],
    grade: "B",
    conditionScore: 86,
    price: 469,
    originalPrice: 899,
    cpu: "Intel Core i5-1240P",
    ram: "8GB LPDDR4x",
    storage: "512GB SSD",
    gpu: "Intel Iris Xe",
    display: "15.6\u2033 FHD OLED",
    battery: "Up to 10 hrs",
    weight: "3.7 lb",
    ports: ["1x USB-C", "2x USB-A", "HDMI"],
    releaseYear: 2022,
    warrantyMonths: 6,
    aiTag: "Best for Students",
    highlights: ["OLED at an entry price", "Numpad included", "Fingerprint login"],
    included: ["65W charger", "Restoration report"],
    rating: 4.4,
    reviewCount: 67,
    inspectionChecks: inspection(),
    benchmarks: [
      { label: "Multi-core", value: 71, max: 100, unit: "pts" },
      { label: "Graphics", value: 50, max: 100, unit: "pts" },
      { label: "Battery efficiency", value: 72, max: 100, unit: "pts" },
    ],
  },
];

export const testimonials = [
  { name: "Priya Raman", role: "Design Lead, Northwind Studio", quote: "The condition score matched exactly what arrived. Genuinely couldn't tell it wasn't new.", rating: 5 },
  { name: "Marcus Idowu", role: "Freelance Editor", quote: "Bought the 16\u2033 M1 Max for half the price of new. Renders exports 8K ProRes without a hiccup.", rating: 5 },
  { name: "Jenna Cho", role: "IT Manager, Alden Health", quote: "We fleet-ordered 40 ThinkPads. Every unit passed our imaging process on the first try.", rating: 5 },
  { name: "Tomás Herrera", role: "Architecture Student", quote: "The AI inspection report gave me more detail than the retail store gave on a brand new machine.", rating: 5 },
  { name: "Aisha Bello", role: "Product Manager", quote: "Trade-in estimate was spot on, and the payout landed two days after they received my old laptop.", rating: 4 },
  { name: "Wei Zhang", role: "Data Scientist", quote: "Battery health was rated 91% and a year later it still holds a full workday of charge.", rating: 5 },
  { name: "Sofia Marin", role: "Motion Designer", quote: "The XPS 15 I bought handles After Effects renders better than my old new-in-box machine did.", rating: 5 },
  { name: "Daniel Okafor", role: "Startup Founder", quote: "Kitted out a five-person team for less than the price of two new laptops.", rating: 5 },
  { name: "Grace Lindqvist", role: "University Researcher", quote: "Warranty support actually picked up the phone. Replaced a keyboard within the week.", rating: 4 },
  { name: "Ben Okafor", role: "Video Editor", quote: "Grade A+ meant zero cosmetic marks. I was expecting at least a scuff.", rating: 5 },
  { name: "Lucia Ferreira", role: "UX Researcher", quote: "The AI assistant actually steered me away from an overpowered (and overpriced) option. Appreciated the honesty.", rating: 5 },
  { name: "Omar Siddiqui", role: "Systems Administrator", quote: "TPM verification listed on the inspection report saved me a support ticket during Windows 11 setup.", rating: 5 },
  { name: "Hannah Voss", role: "Illustrator", quote: "OLED color accuracy on the Zenbook is shockingly close to my calibrated studio monitor.", rating: 4 },
  { name: "Kwame Mensah", role: "Consultant", quote: "Three business trips in and the hinge feels as tight as day one.", rating: 5 },
  { name: "Emilia Novak", role: "Grad Student", quote: "Financed a ThinkPad through their student plan. Cheaper monthly than my coffee budget.", rating: 4 },
  { name: "Rahul Deshmukh", role: "DevOps Engineer", quote: "Ran a full week of CI builds on the P1 without a single thermal throttle.", rating: 5 },
  { name: "Chloe Bennett", role: "Photographer", quote: "Color-critical work on a refurbished machine felt like a gamble. It wasn't.", rating: 5 },
  { name: "Yusuf Karimi", role: "Operations Director", quote: "The bulk order dashboard made outfitting 120 employees almost boring \u2014 in a good way.", rating: 5 },
  { name: "Nina Petrov", role: "Front-end Developer", quote: "Keyboard feel on the X1 Carbon is better than most brand-new laptops I've tried this year.", rating: 5 },
  { name: "Isaac Osei", role: "High School Teacher", quote: "Bought ten Vivobooks for a classroom set. Every single one arrived within the promised week.", rating: 4 },
];

export const stats = {
  laptopsRestored: 214000,
  co2SavedTons: 4820,
  avgSavingsPercent: 46,
  customerRating: 4.8,
  warrantyDefaultMonths: 12,
  inspectionPoints: 42,
};
